### ISSUE TITLE
Maze - server crash if you try to load map with wrong gameid

### ISSUE THREAD

**Issue by litemerafrukt** [dbwebb-se/linux#9]
`games[gameid].currentMap = null;` says poff :)

**Comment by foikila** [comment]
Could you write a test for this? 
Or describe how you can reproduce this?

**Comment by litemerafrukt** [comment]
I saw when I recreated this that I was a bit of in my issue. The server crashes if you pass it _both_ a wrong gameid _and_ a nonexistent mapname:
```bash
$ curl localhost:1337
{"text":"New game initialized","gameid":"46437"}
$ curl localhost:1337/map
["maze-of-doom.json","small-maze.json"]
$ curl localhost:1337/19582/map/small-maz # This causes the server to crash.
```
Server crash message:
```
linux/example/nodejs/maze/maze.js:167
        games[gameid].currentMap = null;
                                 ^

TypeError: Cannot set property 'currentMap' of undefined
    at Object.handler (/Users/Any/dbwebb-kurser/linux/example/nodejs/maze/maze.js:159:33)
    at IncomingMessage.<anonymous> (/Users/Any/dbwebb-kurser/linux/example/nodejs/router/router.js:178:23)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickDomainCallback (node.js:429:17)

```

**Comment by mosbth** [comment]
I'll fix that.
